# Lingjian LAN start: backend + portal + three Vite apps, bound to 0.0.0.0.
#
# Usage:
#   pwsh -NoProfile -ExecutionPolicy Bypass -File .\scripts\start-lan.ps1
#   pwsh ... -HostIp 192.168.1.88
#   pwsh ... -UseTrainedLlm
#   pwsh ... -SkipDeps
#   pwsh ... -BackendOnly

param(
    [string]$Python = '',
    [switch]$BackendOnly,
    [switch]$SkipDeps,
    [int]$BackendPort = 8000,
    [switch]$EnableLlm,
    [switch]$DisableLlm,
    [switch]$UseTrainedLlm,
    [string]$HostIp = ''
)

$ErrorActionPreference = 'Stop'
[Console]::OutputEncoding = [System.Text.UTF8Encoding]::new()

$Root = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
Set-Location -LiteralPath $Root

. (Join-Path $PSScriptRoot 'Resolve-LingjianPython.ps1')

$RunDir = Join-Path $env:TEMP 'LingJian-StartLan'
New-Item -ItemType Directory -Path $RunDir -Force | Out-Null

function New-CmdSetLine {
    param([Parameter(Mandatory)][string]$Name, [Parameter(Mandatory)][string]$Value)
    return 'set "' + $Name + '=' + ($Value -replace '"', '""') + '"'
}

function Write-DevCmd {
    param(
        [Parameter(Mandatory)][string]$Path,
        [Parameter(Mandatory)][string[]]$Lines
    )
    Set-Content -LiteralPath $Path -Value $Lines -Encoding ascii
}

function Start-DevCmdWindow {
    param([Parameter(Mandatory)][string]$CmdPath)
    Start-Process -FilePath $CmdPath
}

function Resolve-LanIPv4 {
    $manual = ($HostIp or '').Trim()
    if ($manual) {
        return $manual
    }
    $candidates = Get-NetIPAddress -AddressFamily IPv4 -ErrorAction SilentlyContinue | Where-Object {
        $_.IPAddress -notlike '127.*' -and
        $_.IPAddress -notlike '169.254.*' -and
        $_.PrefixOrigin -ne 'WellKnown'
    } | Sort-Object InterfaceMetric, SkipAsSource
    $pick = $candidates | Select-Object -First 1
    if (-not $pick) {
        throw '未自动识别到可用 IPv4，请使用 -HostIp 192.168.x.x 手动指定。'
    }
    return $pick.IPAddress
}

function Write-PortalLanEnv {
    param([Parameter(Mandatory)][string]$Ip)
    $path = Join-Path $Root 'fake-science-identify-all\.env.development.local'
    $lines = @(
        '# Auto-generated by scripts/start-lan.ps1 for LAN access'
        ('VITE_USER_APP_ORIGIN=http://' + $Ip + ':3000')
        ('VITE_ADMIN_APP_ORIGIN=http://' + $Ip + ':3001')
        ('VITE_AUDIT_APP_ORIGIN=http://' + $Ip + ':3002')
    )
    Set-Content -LiteralPath $path -Value $lines -Encoding ascii
    return $path
}

if ($EnableLlm -and $DisableLlm) {
    Write-Host 'ERROR: use only one of -EnableLlm or -DisableLlm.' -ForegroundColor Red
    exit 1
}
if ($UseTrainedLlm -and $DisableLlm) {
    Write-Host 'ERROR: -UseTrainedLlm conflicts with -DisableLlm.' -ForegroundColor Red
    exit 1
}

$LanIp = Resolve-LanIPv4
$PortalEnvPath = Write-PortalLanEnv -Ip $LanIp

Write-Host '========================================' -ForegroundColor Cyan
Write-Host (' Lingjian LAN start  Root=' + $Root) -ForegroundColor Cyan
Write-Host (' LAN IP=' + $LanIp) -ForegroundColor Cyan
Write-Host '========================================' -ForegroundColor Cyan

$PythonExe = Resolve-LingjianPython -ExplicitPython $Python
if (-not $PythonExe) {
    Write-Host 'ERROR: 未找到可用的 Python 3.10+。请安装后重试，或使用：' -ForegroundColor Red
    Write-Host '  -Python "C:\Path\python.exe"   或   $env:LINGJIAN_PYTHON="同上"' -ForegroundColor Yellow
    exit 1
}
Write-Host ('python: ' + $PythonExe) -ForegroundColor Yellow
Write-Host ('portal env: ' + $PortalEnvPath) -ForegroundColor DarkGray

$env:PYTHONPATH = $Root

if (-not $SkipDeps) {
    Write-Host 'STEP: pip install -r requirement.txt ...' -ForegroundColor Yellow
    & $PythonExe -m pip install -r (Join-Path $Root 'requirement.txt')
    if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
    if ($EnableLlm -or $UseTrainedLlm) {
        Write-Host 'STEP: verify LLM imports (backend/scripts/check_llm_env.py) ...' -ForegroundColor Yellow
        & $PythonExe (Join-Path $Root 'backend\scripts\check_llm_env.py')
        if ($LASTEXITCODE -ne 0) {
            Write-Host 'ERROR: LLM env does not match this Python; fix deps for the python path printed above.' -ForegroundColor Red
            exit $LASTEXITCODE
        }
    }
}
else {
    Write-Host 'STEP: skipped pip (-SkipDeps)' -ForegroundColor DarkGray
}

Write-Host 'STEP: alembic upgrade head ...' -ForegroundColor Yellow
& $PythonExe -m alembic -c (Join-Path $Root 'backend\alembic.ini') upgrade head
if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

$backendCmd = Join-Path $RunDir 'lingjian-backend-lan.cmd'
$backendLines = [System.Collections.Generic.List[string]]::new()
[void]$backendLines.Add('@echo off')
[void]$backendLines.Add('setlocal')
[void]$backendLines.Add('chcp 65001>nul')
[void]$backendLines.Add((New-CmdSetLine 'LINGJIAN_ROOT' $Root))
[void]$backendLines.Add((New-CmdSetLine 'LINGJIAN_PY' $PythonExe))
[void]$backendLines.Add('cd /d "%LINGJIAN_ROOT%"')
[void]$backendLines.Add('set "PYTHONPATH=%LINGJIAN_ROOT%"')

if ($EnableLlm) {
    [void]$backendLines.Add('set "LINGJIAN_ENABLE_LLM=1"')
}
elseif ($DisableLlm) {
    [void]$backendLines.Add('set "LINGJIAN_ENABLE_LLM=0"')
}

if ($UseTrainedLlm) {
    $llmModelDir = Join-Path $Root 'models\qwen\Qwen2.5-3B-Instruct'
    $llmAdapterDir = Join-Path $Root 'LLM\output\qwen-lora-ocr-sft'
    $llmCfg = Join-Path $llmModelDir 'config.json'
    $llmAdapterW = Join-Path $llmAdapterDir 'adapter_model.safetensors'
    if (-not (Test-Path -LiteralPath $llmCfg)) {
        Write-Host ('ERROR: -UseTrainedLlm requires ' + $llmCfg) -ForegroundColor Red
        exit 1
    }
    if (-not (Test-Path -LiteralPath $llmAdapterW)) {
        Write-Host ('ERROR: -UseTrainedLlm requires ' + $llmAdapterW) -ForegroundColor Red
        exit 1
    }
    $llmModelAbs = (Resolve-Path -LiteralPath $llmModelDir).Path
    $llmAdapterAbs = (Resolve-Path -LiteralPath $llmAdapterDir).Path
    [void]$backendLines.Add((New-CmdSetLine 'LINGJIAN_LLM_MODEL' $llmModelAbs))
    [void]$backendLines.Add((New-CmdSetLine 'LINGJIAN_LLM_ADAPTER' $llmAdapterAbs))
    [void]$backendLines.Add((New-CmdSetLine 'LINGJIAN_ENABLE_LLM' '1'))
}

[void]$backendLines.Add(('title Lingjian Backend LAN :' + $BackendPort))
[void]$backendLines.Add('call "%LINGJIAN_PY%" -m uvicorn backend.app.main:app --host 0.0.0.0 --port ' + [string]$BackendPort)
[void]$backendLines.Add('echo.')
[void]$backendLines.Add('echo Backend exited. Press any key to close.')
[void]$backendLines.Add('pause >nul')
Write-DevCmd -Path $backendCmd -Lines $backendLines

Write-Host ('STEP: starting backend (LAN). Docs: http://' + $LanIp + ':' + [string]$BackendPort + '/docs') -ForegroundColor Green
Start-DevCmdWindow -CmdPath $backendCmd

if ($BackendOnly) {
    Write-Host ('Done (backend only). LAN API: http://' + $LanIp + ':' + [string]$BackendPort) -ForegroundColor Green
    exit 0
}

$node = Get-Command node -ErrorAction SilentlyContinue
$npm = Get-Command npm -ErrorAction SilentlyContinue
if (-not $node -or -not $npm) {
    Write-Host 'ERROR: node or npm not in PATH. Install Node 18+ then retry.' -ForegroundColor Red
    exit 1
}

$apps = @(
    @{ Dir = 'fake-science-identify-all'; Title = 'Lingjian Portal (main) :3080'; Port = 3080 },
    @{ Dir = 'fake-science-identify-user'; Title = 'Lingjian User :3000'; Port = 3000 },
    @{ Dir = 'fake-science-identify-admin'; Title = 'Lingjian Admin :3001'; Port = 3001 },
    @{ Dir = 'fake-science-identify-audit'; Title = 'Lingjian Audit :3002'; Port = 3002 }
)

foreach ($a in $apps) {
    $dirPath = Join-Path $Root $a.Dir
    if (-not (Test-Path -LiteralPath $dirPath)) {
        continue
    }
    if (-not $SkipDeps) {
        $nm = Join-Path $dirPath 'node_modules'
        if (-not (Test-Path -LiteralPath $nm)) {
            Write-Host ('STEP: npm install in ' + $a.Dir + ' ...') -ForegroundColor Yellow
            Push-Location -LiteralPath $dirPath
            npm install
            if ($LASTEXITCODE -ne 0) {
                Pop-Location
                exit $LASTEXITCODE
            }
            Pop-Location
        }
    }
    $safeName = ($a.Dir -replace '[^a-zA-Z0-9_-]', '_')
    $viteCmd = Join-Path $RunDir ('lingjian-lan-vite-' + $safeName + '.cmd')
    $viteLines = @(
        '@echo off'
        'setlocal'
        'chcp 65001>nul'
        (New-CmdSetLine 'APP_DIR' $dirPath)
        'cd /d "%APP_DIR%"'
        ('title ' + $a.Title)
        'npm run dev -- --host 0.0.0.0'
        'echo.'
        'echo Vite exited. Press any key to close.'
        'pause >nul'
    )
    Write-DevCmd -Path $viteCmd -Lines $viteLines
    Start-DevCmdWindow -CmdPath $viteCmd
}

Write-Host
Write-Host 'Started in new windows (LAN mode).' -ForegroundColor Cyan
Write-Host ('  API docs        http://' + $LanIp + ':' + [string]$BackendPort + '/docs')
Write-Host ('  Portal          http://' + $LanIp + ':3080')
Write-Host ('  User UI         http://' + $LanIp + ':3000')
Write-Host ('  Admin UI        http://' + $LanIp + ':3001')
Write-Host ('  Audit UI        http://' + $LanIp + ':3002')
Write-Host
Write-Host 'Windows Defender may ask for firewall permission the first time.' -ForegroundColor DarkYellow
